ws:
    cd /workspace/crates/static-website && cargo watch --workdir /workspace/crates/static-website -w ./content -w ./src --no-gitignore -x "run --bin static-website"

wts:
    cd /workspace/crates/static-website && /workspace/scripts/tailwind-crates --input ./input.css --output ./dist/tailwind.css --watch
