apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: one-runtime
  namespace: one-runtime
spec:
  components:
    db: {}
  profiles:
    dev:
      components:
        oidc:
          hostname-url: http://localhost:32760
        ingress:
          port: 32760
        db:
          expose_db_port: 32761
          danger_override_password: testpassword
    prod:
      components:
        oidc:
          # Required by keycloak for OIDC. OIDC requires a stable redirect URL.
          hostname-url: https://app.one-runtime.com
  services:
    web:
      image: ghcr.io/purton-tech/one-runtime:1.0.0
      port: 3000
      database_url: APPLICATION_URL
      init:
        image: ghcr.io/purton-tech/one-runtime-migrations:1.0.0
        migrations_database_url: DATABASE_URL