name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.15

      - name: Run Earthly CI build
        run: earthly --ci +all
